import type { Metadata } from "next";
import { Mrs_Sheppards } from "next/font/google";
import "./globals.css";

const mrsSheppards = Mrs_Sheppards({
  subsets:['latin'],
  weight:["400"]

})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${mrsSheppards.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
